import { Migration } from '@mikro-orm/migrations';

export class Migration20260926000000 extends Migration {

  override name = 'Migration20260926000000';

  override up(): void | Promise<void> {
    this.addSql(`create table "document" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "retention_anonymized_at" timestamptz null, "source_key" text not null, "external_id" text not null, "version" int not null, "title" text not null, "url" text not null, "published_at" text null, "license" text null, "license_scope" text not null, "is_case_report" boolean not null, "status" text not null, "content_hash" text not null, "mesh_descriptor_uis" text[] not null, "superseded_at" timestamptz null, primary key ("id"));`);
    this.addSql(`alter table "document" add constraint "document_source_key_external_id_version_unique" unique ("source_key", "external_id", "version");`);
    this.addSql(`alter table "document" add constraint "document_status_check" check ("status" in ('current', 'superseded', 'retracted'));`);
    this.addSql(`alter table "document" add constraint "document_license_scope_check" check ("license_scope" in ('full_text', 'excerpt_only', 'metadata_only'));`);
    // at most one live (current or retracted) row per source document
    this.addSql(`create unique index "document_live_version_unique" on "document" ("source_key", "external_id") where "status" <> 'superseded';`);
    this.addSql(`create index "document_mesh_descriptor_uis_index" on "document" using gin ("mesh_descriptor_uis");`);

    // search_vector is generated by PostgreSQL, so full-text search can never
    // drift from the passage text.
    this.addSql(`create table "document_chunk" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "retention_anonymized_at" timestamptz null, "document_id" uuid not null, "section_path" text not null, "ordinal" int not null, "text" text not null, "embedding" vector null, "embedding_model" text null, "search_vector" tsvector generated always as (to_tsvector('english', coalesce("section_path", '') || ' ' || coalesce("text", ''))) stored, primary key ("id"));`);
    this.addSql(`alter table "document_chunk" add constraint "document_chunk_document_id_foreign" foreign key ("document_id") references "document" ("id") on update cascade on delete cascade;`);
    this.addSql(`create index "document_chunk_document_id_index" on "document_chunk" ("document_id");`);
    this.addSql(`create index "document_chunk_search_vector_index" on "document_chunk" using gin ("search_vector");`);
    // No vector index yet: an HNSW index needs a fixed dimension, which is
    // set once the embedding model is chosen. Exact search works without it.

    this.addSql(`create table "medical_concept" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "retention_anonymized_at" timestamptz null, "descriptor_ui" text not null, "preferred_term" text not null, "synonyms" text[] not null, "tree_numbers" text[] not null, primary key ("id"));`);
    this.addSql(`alter table "medical_concept" add constraint "medical_concept_descriptor_ui_unique" unique ("descriptor_ui");`);
  }

  override down(): void | Promise<void> {
    this.addSql(`drop table if exists "document_chunk" cascade;`);
    this.addSql(`drop table if exists "document" cascade;`);
    this.addSql(`drop table if exists "medical_concept" cascade;`);
  }

}
