packages:
  - common
  - core
  - express
  - hyper-express
  - universal-sdk
  - validator
  - testing
  - e2e-tests
  - infrastructure/redis
  - infrastructure/S3
  - internal
  - bunrun
  - ws

onlyBuiltDependencies:
  - "@scarf/scarf"
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
  - tldjs
  - unrs-resolver
