/**
 * Platform event handlers by feature. Generated by `forklaunch infra add`;
 * edit the handler files, not this list.
 */
import type { PlatformEvent } from '@forklaunch/core/http';
import { handle as paymentsEvents } from './payments';

export const platformEventHandlers: Record<
  string,
  (event: PlatformEvent) => Promise<void>
> = {
  payments: paymentsEvents,
};
