import { createHmacToken } from '@forklaunch/core/http';
import { randomUUID } from 'node:crypto';
const S='dev-hmac-secret-key-for-catalog-import-000',B='http://localhost:8001';
const A=(m:string,p:string,b?:unknown)=>{const t=new Date(),n=randomUUID();return `HMAC keyId=default ts=${t.toISOString()} nonce=${n} signature=${createHmacToken({method:m,path:p,body:b,timestamp:t,nonce:n,secretKey:S})}`;};
const c=async(m:string,u:string,sp:string,b?:unknown)=>{const r=await fetch(B+u,{method:m,headers:{'content-type':'application/json',authorization:A(m,sp,b)},body:b?JSON.stringify(b):undefined});return{code:r.status,body:await r.json().catch(()=>null)};};
let r=await c('GET','/product/handle/hot-sauce','/handle/hot-sauce');const pid=r.body.id;
r=await c('GET',`/variant/product/${pid}`,`/product/${pid}`);const vid=r.body[0].id;
r=await c('POST','/cart','/',{customerId:'x'});const cid=r.body.id;
await c('POST','/cart/items','/items',{cartId:cid,variantId:vid,quantity:2});
r=await c('GET',`/cart/${cid}`,`/${cid}`);
console.log(JSON.stringify(r.body,null,1).slice(0,600));
